name: trivve
description: A social arcade and mapping app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Map & Location (Consolidated)
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.1
  url_launcher: ^6.2.0

  # Firebase Core & Auth
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

  # UI & Utilities
  confetti: ^0.7.0
  share_plus: ^10.1.0
  google_generative_ai: ^0.4.6
  cupertino_icons: ^1.0.8
  package_info_plus: ^9.0.0

# To take the photo
  image_picker: ^1.0.7       
  flutter_image_compress: ^2.1.0 # To shrink it to 150KB
  cached_network_image: ^3.3.1   # To save bandwidth (don't re-download same pics)
  google_fonts: ^6.2.1
  timeago: ^3.6.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true