name: trivve
description: A real-time college & city discovery app
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.5.0

  google_fonts: ^6.2.1

flutter:
  uses-material-design: true
